name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'   # run only on vX.Y.Z tags

jobs:
  publish-npm:
    name: Build & publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true

      # Ensure npm has the token even if a repo .npmrc exists
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build (must emit dist/modbus-webui.html)
        run: npm run build

      - name: Sanity check single-file output
        run: test -f dist/modbus-webui.html

      - name: Ensure CLI is executable
        run: chmod +x bin/cli.mjs

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
